#pragma once

enum
{
	XT_FILE_ATTR_READONLY = 0,
	XT_FILE_ATTR_HIDDEN = 1,
	XT_FILE_ATTR_SYSTEM = 2,
	XT_FILE_ATTR_DIR = 4,
	XT_FILE_ATTR_ARCHIVE = 5,
	XT_FILE_ATTR_LINK = 6,
	XT_FILE_ATTR_EXECUTABLE = 7,
};
