#pragma once
// XBase Palette manamger (pal)
// (c) Michael Moffitt 2024
//
// X68000 palette memory is $400 bytes in size, organized like so:
//
// 0xE82000 | Graphic Plane palette 0
//          | ~
// 0xE821E0 | Graphic Plane palette 15
// 0xE82200 | PCG palette 0, Text palette
// 0xE82220 | PCG palette 1
//          | ~
// 0xE823E0 | PCG palette 15
//
// Palette data is placed into a buffer, and that buffer is committed to
// palette memory when xb_pal_commit() is called.
//
// Palette lines (32-byte array of color data) can be written to the buffer
// with xb_pal_set(), which automatically marks that line as needing a transfer.
//
// Alternatively, you may directly manipulate g_xb_pal_buffer, but must be sure
// to mark the row(s) 
#ifndef __ASSEMBLER__
#include <stdint.h>
#include "xbase/memmap.h"
#endif

// Starting row definitions. There are sixteen row within the GP section,
// and sixteen more in the PCG section. The text palette is shared with
// PCG palette 0 (so, row 16).
#define XB_PAL_GP 0
#define XB_PAL_TEXT 16
#define XB_PAL_PCG 16

#ifdef __ASSEMBLER__
	.global	xb_pal_init
	.global	xb_pal_set
	.global	xb_pal_fill
	.global	xb_pal_mark
	.global	xb_pal_commit

	.global	g_xb_pal_buffer
#else

extern uint16_t g_xb_pal_buffer[0x200];

// Initializes palette manager by clearing palette buffer and requesting a
// full transfer (clear to black).
void xb_pal_init(void);

// Copies a 16-color palette into the buffer and marks it for uploading.
void xb_pal_set(uint16_t row, const void *src);

// Fills a row with a single color.
void xb_pal_fill(uint16_t row, uint16_t value);

// Mark row(s) as in need of a transfer to color memory.
// The bitfield data can be generated by using XB_BITVAL() with the row index
// as the bit.
// row_bitfield is organized such that GP palette 0 is the LSB,
// text/PCG0 is bit 16, so on and so forth. All rows can be transmitted
// by specifying 0xFFFFFFFF (all bits set).
void xb_pal_mark(uint32_t row_bitfield);

// Copy data from the palette buffer to color memory. Call during vblank.
void xb_pal_commit(void);

#endif
